updated scripts - rotated makematrix and included velocity graphs

diff --git a/scripts/jobstat b/scripts/jobstat
--- a/scripts/jobstat
+++ b/scripts/jobstat
@@ -1,80 +1,116 @@
+#!/usr/bin/env bash
 
 #BASEDIR="/cluster/runs"
-#HOSTS="b1 b2 b3 b4"
+#HOSTS="b1 b2 b3 b4 b5"
 
 echo
 
-date
+#date
 source comet_script_settings
 
-#SCREENS=`screen -list | sort +1`
-
 FREENODES=0
+NODESDOWN=0
 
-echo "   Machine  1mld  5mld       ID      R             Frame"
+tempdir=`mktemp -d /tmp/jobstat.XXXXXX` || exit 1
 
-(for MACHINE in $HOSTS
+screen -list > $tempdir/screenlist.txt
+
+touch  $tempdir/unsorted.txt
+touch  $tempdir/errors.txt
+touch  $tempdir/errors2.txt
+
+echo -n Scanning hosts
+
+for MACHINE in $HOSTS
 do
-REMOTEUPTIME=`ssh -x $MACHINE "uptime"`
-LOAD1MIN=$(echo $REMOTEUPTIME | awk -F "load avera.*:" '{ print $2 }' | cut -d, -f1)
-LOAD5MIN=$(echo $REMOTEUPTIME | awk -F "load avera.*:" '{ print $2 }' | cut -d, -f2)
-SCREEN=`screen -list | grep $MACHINE | cut -d. -f2`
+	#echo -n " Host $MACHINE: " >&2
+	echo -n .
 
-MACHINE=`printf "% 10s" $MACHINE`
+	REMOTEUPTIME=`ssh -oConnectTimeout=1 -x $MACHINE "uptime" 2>>$tempdir/errors2.txt`
+	if [ "$?" -eq 255 ] ; then
+		echo -n "HOST $MACHINE IS DOWN (" >> $tempdir/errors.txt
+		echo -n ")" | cat $tempdir/errors2.txt - | tr -d '\n' | tr -d '\r'  >> $tempdir/errors.txt
+		rm $tempdir/errors2.txt
+		touch  $tempdir/errors2.txt
+		((NODESDOWN=NODESDOWN+1))
+		continue
+	fi
+	LOAD1MIN=$(echo $REMOTEUPTIME | awk -F "load avera.*:" '{ print $2 }' | cut -d, -f1)
+	LOAD5MIN=$(echo $REMOTEUPTIME | awk -F "load avera.*:" '{ print $2 }' | cut -d, -f2)
+	SCREEN=`grep $MACHINE $tempdir/screenlist.txt | cut -d. -f2`
 
-IDENTIFIER=${SCREEN%_?_*}
+	MACHINE=`printf "% 10s" $MACHINE`
 
+	IDENTIFIER=${SCREEN:0:13}
 
-# we had to replace / with - for the sym runs to get screen to work, so replace back here
-IDENTIFIER=${IDENTIFIER//sym-sym/sym/sym}
+	if [ ! "$IDENTIFIER" == "" ]; then
 
-#IDENTIFIER=`echo $SCREEN | cut -c 1-13 `
+		IDEN2=${SCREEN:14:100}
 
-#echo $IDFULL
+		HOST=${IDEN2#*_}
 
-IDFULL=${SCREEN%_*}
-RUN=${IDFULL#*_*_}
+		RUN=${IDEN2%_*}
 
-#RUN=`echo $SCREEN | cut -c 15-15 `
+		INFOFILE="$BASEDIR/${IDENTIFIER}/${RUN}/comet_run_info.txt"
+		SYMBREAKFILE="$BASEDIR/${IDENTIFIER}/${RUN}/sym_break_axis.txt"
+		#echo $INFOFILE >&2
 
-INFOFILE="$BASEDIR/${IDENTIFIER}/${RUN}/comet_run_info.txt"
-SYMBREAKFILE="$BASEDIR/${IDENTIFIER}/${RUN}/sym_break_axis.txt"
-#echo $INFOFILE
+		# find frame number from end of info file
 
-FRAME=""
+		FRAME=""
 
-if [ -f $INFOFILE ] ; then
-FRAME=`tail -1 $INFOFILE | cut -c45-80 `
+		if [ -f $INFOFILE ] ; then
+			FRAME=`tail -1 $INFOFILE | cut -c45-80 `
+		fi
+
+		# add a '*' if not broken sym
+
+		if [ ! -f $SYMBREAKFILE ] ; then
+			FRAME="$FRAME *"
+		fi
+		
+		# count free nodes
+		grep -q $MACHINE $tempdir/screenlist.txt
+		if [ "$?" -eq "1" ] ; then 
+			(( FREENODES = FREENODES + 1))
+		fi
+		
+else
+
+	IDENTIFIER="(no job running)"
+
 fi
 
-# add a '*' if not broken sym
+	RUN=`printf %2s $RUN`
+	echo "$MACHINE $LOAD1MIN $LOAD5MIN $IDENTIFIER $RUN $FRAME" >> $tempdir/unsorted.txt
+done
+echo
+cat $tempdir/errors.txt
 
-if [ ! -f $SYMBREAKFILE ] ; then
-FRAME="$FRAME *"
-fi
+echo
+echo
+echo "   Machine  1mld  5mld       ID       R       T     Frame"
+
+cat $tempdir/unsorted.txt | sort -k1
 
 
-echo "$MACHINE $LOAD1MIN $LOAD5MIN $IDENTIFIER $RUN $FRAME"
-done) | sort -k1
-
-
-#count free nodes:
-
-#for MACHINE in $HOSTS
-#do
-#SCREEN=`screen -list | grep $MACHINE`
-
-#if [ `screen -list | grep -q $MACHINE` ] ; then 
-#(( FREENODES = FREENODES + 1))
-#fi
-
+rm $tempdir/screenlist.txt $tempdir/unsorted.txt $tempdir/errors.txt $tempdir/errors2.txt
+rmdir $tempdir
 
 #done
 echo
 
 echo $FREENODES nodes free
 
-WAITINGJOBS=`wc -l $BASEDIR/joblist | cut -d ' ' -f1 `
+if [ -f $BASEDIR/joblist ]; then
+	WAITINGJOBS=`wc -l $BASEDIR/joblist | cut -d ' ' -f1 `
+	echo $WAITINGJOBS jobs waiting
+else
+	echo "No joblist file found ($BASEDIR/joblist)"
+fi
 
-echo $WAITINGJOBS jobs waiting
+if [ "$NODESDOWN" -ne "0" ]; then
+	echo "$NODESDOWN nodes down!"
+fi
+
 echo
